export const genreList =[
    {
        genre:"FICTION",
        icon:"/images/Fiction.svg"
    },
    {
        genre:"DRAMA",
        icon:"/images/Drama.svg"
    },
    {
        genre:"HUMOUR",
        icon:"/images/Humour.svg"
    },
    {
        genre:"POLITICS",
        icon:"/images/Politics.svg"
    },
    {
        genre:"PHILOSOPHY",
        icon:"/images/Philosophy.svg"
    },
    {
        genre:"HISTORY",
        icon:"/images/History.svg"
    },
    {
        genre:"ADVENTURE",
        icon:"/images/Adventure.svg"
    },

]
